services:
  - type: web
    name: marigold-disease-prediction-backendd
    env: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: SKIP_ML
        value: "true"
  - type: static
    name: marigold-disease-frontend
    env: static
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://marigold-disease-prediction-backendd.onrender.com"
